### ISSUE TITLE
API access error

### ISSUE THREAD

**Issue by eydun** [cagatayy94/spotify-api-consumer#2]
Thanks for making this project.

I have installed it locally. But when I try to search I get the error "API access error".

What do I set for "APP_TO_SPOTIFY_SECRET"?

**Comment by cagatayy94** [comment]
1. You should login at here https://developer.spotify.com/dashboard/applications
2. You should get your own secret and id from there.
3. Create new app and you will see your secret and id inside the app which you created now.

**Comment by eydun** [comment]
Thanks!
