### ISSUE TITLE
Order columns

### ISSUE THREAD

**Issue by eydun** [cagatayy94/spotify-api-consumer#3]
This is a feature request.

It would be cool if it was possible to click on column-names to sort by their values.
![image](https://user-images.githubusercontent.com/12867/108592321-42878180-7365-11eb-9790-907ab36056d9.png)

**Comment by cagatayy94** [comment]
Yes. Thanks for advice. But I am currently working on projects below.

https://github.com/cagatayy94/angular-shop
https://github.com/cagatayy94/.net-skeleton
https://github.com/cagatayy94/.net-recap-project

I don't have much time to add this feature. 
If you want to develop this feature I can add you as a collaborator on this project.
