### ISSUE TITLE
Search for Genre

### ISSUE THREAD

**Issue by eydun** [cagatayy94/spotify-api-consumer#4]
Feature request: 

If would be great if it was possible to search for genres.

**Comment by cagatayy94** [comment]
Yes. Thanks for advice. But I am currently working on projects below.

https://github.com/cagatayy94/angular-shop
https://github.com/cagatayy94/.net-skeleton
https://github.com/cagatayy94/.net-recap-project

I don't have much time to add this feature. 
If you want to develop this feature I can add you as a collaborator on this project.
